name: Setup project
description: Setup project dependencies
inputs:
  run_install:
    description: 'Set to true to install dependencies, false to skip.'
    required: false
    default: 'true'
  run-playwright-install:
    description: 'Set to true to run yarn playwright install, false to skip.'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup CI Enviroment Variable
      shell: bash
      run: export CI=true

    - name: Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: .nvmrc
        registry-url: 'https://registry.npmjs.org'

    - name: Cache data for pnpm and node_modules
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: |
          ~/.pnpm-store
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        version: 10

    - shell: bash
      run: pnpm install --frozen-lockfile

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      if: ${{ inputs.run-playwright-install == 'true' }}
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install playwright deps
      if: ${{ inputs.run-playwright-install == 'true' }}
      shell: bash
      run: ./node_modules/.bin/playwright install --with-deps chromium