name: Setup project
description: Setup project dependencies
inputs:
  run_install:
    description: "Set to true to install dependencies, false to skip."
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Setup CI Enviroment Variable
      shell: bash
      run: export CI=true

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        registry-url: "https://registry.npmjs.org"

    - name: Cache data for pnpm and node_modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - shell: bash
      run: pnpm install --frozen-lockfile
