services:
  icons:
    container_name: icons
    build:
      context: ..
      dockerfile: apps/icons/Dockerfile
    networks:
      ecomma:
        ipv4_address: 10.10.28.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:80']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  home-site:
    container_name: home-site
    build:
      context: ..
      dockerfile: apps/home-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:4000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  accounts-site:
    container_name: accounts-site
    build:
      context: ..
      dockerfile: apps/accounts-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.2
    extra_hosts:
      - icons.fbi.com:10.10.10.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:4000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  admin-site:
    container_name: admin-site
    build:
      context: ..
      dockerfile: apps/admin-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.3
    extra_hosts:
      - icons.fbi.com:10.10.10.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:4000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  app-site:
    container_name: app-site
    build:
      context: ..
      dockerfile: apps/app-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.4
    extra_hosts:
      - icons.fbi.com:10.10.10.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:4000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  iam-service:
    container_name: iam-service
    build:
      context: ..
      dockerfile: apps/iam-service/Dockerfile
      target: debug
    environment:
      MONGODB_URI: mongodb://user:password@mongodb:27017
      RABBITMQ_URI: amqp://rabbitmq:5672
      LOG_FORMAT: text
      LOG_LEVEL: debug
    networks:
      ecomma:
        ipv4_address: 10.10.60.1
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:3000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  ndm-service:
    container_name: ndm-service
    build:
      context: ..
      dockerfile: apps/ndm-service/Dockerfile
      target: debug
    environment:
      MONGODB_URI: mongodb://user:password@mongodb:27017
      RABBITMQ_URI: amqp://rabbitmq:5672
      SMTP_URI: smtp://maildev:1025?secure=false
      LOG_FORMAT: text
      LOG_LEVEL: debug
    networks:
      ecomma:
        ipv4_address: 10.10.60.2
    healthcheck:
      test: ['CMD', 'wget', '--spider', '--quiet', 'http://127.0.0.1:3000/health']
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s
