services:

  icons:
    container_name: icons
    build:
      context: ..
      dockerfile: apps/icons/Dockerfile
    networks:
      ecomma:
        ipv4_address: 10.10.28.1
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:80"]
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s


  home-site:
    container_name: home-site
    build:
      context: ..
      dockerfile: apps/home-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.1
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:4000"]
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  accounts-site:
    container_name: accounts-site
    build:
      context: ..
      dockerfile: apps/accounts-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.2
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:4000"]
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  admin-site:
    container_name: admin-site
    build:
      context: ..
      dockerfile: apps/admin-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.3
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:4000"]
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s

  app-site:
    container_name: app-site
    build:
      context: ..
      dockerfile: apps/app-site/Dockerfile
      target: debug
    networks:
      ecomma:
        ipv4_address: 10.10.30.4
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://127.0.0.1:4000"]
      interval: 5s
      timeout: 8s
      retries: 10
      start_period: 10s
