name: Run nx affected
description: Determine Nx Affected Base and Head SHA and run command
inputs:
  targets:
    description: 'nx affected arguments'
    required: true
  workers:
    description: 'nx affected arguments'
    required: false
    default: '12'
runs:
  using: composite
  steps:
    - name: Determine Nx Affected Base and Head
      shell: bash
      run: |
        BASE="origin/main"
        HEAD="${{ github.sha }}"

        # Fetch all tags to ensure the latest tag is available
        git config --global --add safe.directory /__w/application/application
        git fetch origin --tags --no-recurse-submodules

        # Get the SHA of the latest tag on origin/main
        # This command finds the latest tag that is reachable from origin/main
        LATEST_TAG_SHA=$(git rev-list --tags --max-count=1 --date-order origin/main)

        if [ -z "$LATEST_TAG_SHA" ]; then
          echo "No tags found on origin/main. Defaulting BASE to origin/main."
          BASE="origin/main"
        else
          echo "Latest tag SHA on origin/main: $LATEST_TAG_SHA"
          BASE="$LATEST_TAG_SHA"
        fi

        # For pull_request_target, use the base branch of the PR
        if [ "${{ github.event_name }}" == "pull_request_target" ]; then
          BASE="origin/${{ github.base_ref }}"
          HEAD="origin/${{ github.head_ref }}"
          echo "Running on pull_request_target. Base: $BASE, Head: $HEAD"
        fi

        # For merge_group, the base is the merge group ref and head is the current commit
        if [ "${{ github.event_name }}" == "merge_group" ]; then
          BASE="${{ github.base_ref }}"
          HEAD="${{ github.sha }}"
          echo "Running on merge_group. Base: $BASE, Head: $HEAD"
        fi

        echo "NX_AFFECTED_BASE=$BASE" >> $GITHUB_ENV
        echo "NX_AFFECTED_HEAD=$HEAD" >> $GITHUB_ENV

    - name:  Run nx affected target
      shell: bash
      run: npx nx affected --base=$NX_AFFECTED_BASE --head=$NX_AFFECTED_HEAD --targets=${{ inputs.targets}} --parallel=${{ inputs.workers}}
