name: Intergration

on:
  push:
    branches:
      - main
      - dev

  pull_request_target:
    branches:
      - main
      - dev

  merge_group:
    branches:
      - main
      - dev
env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

permissions:
  contents: write
  pull-requests: write
jobs:
  validation:
    name: Code quality validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run lint projects
        run: npx nx affected --targets=lint --base=origin/main --parallel 12

      - name: Run unit tests
        run: npx nx affected --targets=test --base=origin/main

      - name: Run build
        run: npx nx affected --targets=build --base=origin/main

  automation-test:
    name: Automation Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          run-playwright-install: true

      - name: Run containerize docker images
        run: npx nx affected --targets=containerize --base=origin/main --parallel 1

      - name: Automate Integration
        run: npx nx affected --target=automate-integration-test --base=origin/main --parallel 1

      - name: Automate E2E Test
        run: npx nx affected --target=automate-e2e-test --base=origin/main --parallel 1

  release:
    name: Release
    needs: [validation, automation-test]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      - uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release-please
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          config-file: release.config.json
          manifest-file: release.manifest.json
