name: Intergration

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

  pull_request_target:
    branches:
      - main
      - dev

  merge_group:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        uses: nrwl/nx-set-shas@v4

      - name: Lint Affected Projects (Pull Request / Target)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: npx nx affected --target=lint

      - name: Lint All Projects (Push / Merge Group)
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        run: npx nx run-many --target=lint --all # --all là tùy chọn, nhưng thường được dùng với run-many

      - name: Unit Test Affected Projects (Pull Request / Target)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: npx nx affected --target=test

      - name: Unit Test All Projects (Push / Merge Group)
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        run: npx nx run-many --target=test --all

      - name: Build Affected Projects (Pull Request / Target)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: npx nx affected --targets=build,containerize

      - name: Build All Projects (Push / Merge Group)
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        run: npx nx run-many --targets=build,containerize --all

  intergration:
    name: Intergration Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        uses: nrwl/nx-set-shas@v4

      - name: Automate Integration Test Affected Projects (Pull Request / Target)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: npx nx affected --target=automate-integration-test

      - name: Automate Integration Test All Projects (Push / Merge Group)
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        run: npx nx run-many --target=automate-integration-test --all

  e2e:
    name: E2E Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          run-playwright-install: true

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        uses: nrwl/nx-set-shas@v4

      - name: Automate E2E Test Affected Projects (Pull Request / Target)
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        run: npx nx affected --target=automate-e2e-test

      - name: Automate E2E Test All Projects (Push / Merge Group)
        if: ${{ github.event_name == 'push' || github.event_name == 'merge_group' }}
        run: npx nx run-many --target=automate-e2e-test --all

  release:
    name: Release
    needs: [validation, intergration, e2e]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          config-file: release.config.json
          manifest-file: release.manifest.json
