name: Intergration

on:
  push:
    branches:
      - main
      - dev

  pull_request_target:
    branches:
      - main
      - dev

  merge_group:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write
jobs:
  # Job mới: Linting
  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Lint All Projects
        run: npx nx affected --targets=lint --base=origin/main

  # Job mới: Unit Test
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Run Unit Tests
        run: npx nx affected --target=test --base=origin/main

  # Job mới: Build & Containerize
  build:
    name: Build Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Build All Projects
        run: npx nx affected --targets=build --base=origin/main

  containerize:
    name: Containerize Projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Build All Projects
        run: npx nx affected --targets=containerize --base=origin/main

  intergration-test:
    name: Intergration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Automate Integration Test All Projects
        run: npx nx affected --target=automate-integration-test --base=origin/main

  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ecoma-io/playwright-runner:1.2.0
      options: --privileged
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup project
        uses: ./.github/actions/setup

      - name: Fetch origin/main
        run: |
          git config --global --add safe.directory .
          git fetch origin main:origin/main --no-tags --force

      - name: Automate E2E Test All Projects
        run: npx nx affected --target=automate-e2e-test --base=origin/main

  release:
    name: Release
    needs: [lint, unit-test, build, intergration-test, e2e-test, containerize]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: googleapis/release-please-action@v4
        id: release-please
        with:
          token: ${{ secrets.GH_BOT_TOKEN }}
          config-file: release.config.json
          manifest-file: release.manifest.json
